### ISSUE TITLE
Problems with the stable and development collection -24

### ISSUE THREAD

**Issue by jcarolinares** [Obijuan/Academia-Jedi-Hw#1]
Hello

I'm receiving a 404 in the stable download link. The development link works fine, however Icestudio tell me that it is an invalid collection, don't know why

Thanks for this amazing collection of blocks!

**Comment by jcarolinares** [comment]
Icestudio version: 5.0.0-dev

**Comment by jcarolinares** [comment]
Closed by myself, not important due to there are more newer releases of the collections that are working.

**Comment by Obijuan** [comment]
The collection used in the Academy are incremental. The n+1 collection contains the blocks of the n collection + the new blocks added.

Instead of using the Academy collections, i recommend you to use the Jedi Collection: 

https://github.com/FPGAwars/Collection-Jedi

It contains all the blocks showed int he Academy + much much more
